name: PoweredMobs
version: '${project.version}'
main: adhdmc.poweredmobs.PoweredMobs
api-version: 1.19
authors: [ Peashooter101 ]
description: Simple plugin for light configuration and customization of mobs.
